<div class="form-style-8">
  <h2>Login to your account</h2>
  <form>
    <input type="text" name="field1" placeholder="Full Name" />
    <input type="email" name="field2" placeholder="Email" />
    <input type="url" name="field3" placeholder="Website" />
    <textarea placeholder="Message" onkeyup="adjust_textarea(this)"></textarea>
    <input type="button" value="Send Message" />
  </form>
</div>
<script type="text/javascript">
//auto expand textarea
function adjust_textarea(h) {
    h.style.height = "20px";
    h.style.height = (h.scrollHeight)+"px";
}
</script>